  name: build
  on:
    push:
      branches:
        - master
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repository
          uses: actions/checkout@v4
        - name: validate gradle wrapper
          uses: gradle/actions/wrapper-validation@v4
        - name: setup jdk 8.0
          uses: actions/setup-java@v4
          with:
            distribution: adopt
            java-version: 8.0
        - name: make gradle wrapper executable
          run: chmod +x ./gradlew
        # 第一次构建
        - name: build
          continue-on-error: true
          id: build_1
          run: ./gradlew build
        # 第二次构建
        - name: build (retry)
          continue-on-error: true
          id: build_2
          if: steps.build_1.outcome == 'failure'
          run: ./gradlew build
        # 构建API
        - name: build (api)
          id: build_api
          run: ./gradlew taboolibBuildApi
        # 上传构建文件
        - name: capture build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: Artifacts
            path: build/libs/